// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:fd637211-d892-45e3-8e41-ba7792063225",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_F0TnghJoe",
    "aws_user_pools_web_client_id": "g071sp7e3t7ppl19opv8s0q3v"
};


export default awsmobile;
